"""Lightweight speaker verification — numpy only, no ML runtime.

Utterance embedding = statistics of log-mel band energies over voiced frames
(spectral envelope carries most of the speaker's timbre). Profile = mean of
enrollment embeddings; score = cosine similarity. This is honest v1 signal for
"does the current speaker sound like the owner", NOT biometric auth — the
bridge only annotates, never blocks. The default threshold is tuned by
``dojo/run_dojo.py`` against a matrix of ElevenLabs voices.
"""

from __future__ import annotations

import numpy as np

SAMPLE_RATE = 16000
FRAME = 400        # 25 ms
HOP = 160          # 10 ms
N_MELS = 32
N_FFT = 512

# Tuned by dojo/run_dojo.py (threshold sweep → equal-error point on the
# ElevenLabs voice matrix). Overridable via plugin_voice.settings["threshold"].
DEFAULT_THRESHOLD = 0.90  # replaced by dsp_calibration.THRESHOLD when present

# What the owner reads during enrollment — phonetically varied, natural pace.
ENROLL_PHRASES = [
    "Hey, it's me — I'm setting up my voice so you can recognize me later.",
    "The quick brown fox jumps over the lazy dog, twice on Sundays.",
    "Would you check my calendar, the weather, and anything urgent this morning?",
    "Seven, three, nineteen, forty two — numbers sound different in every voice.",
    "Alright, that should be enough for you to know exactly how I sound.",
]
MIN_ENROLL = 4


def pcm_to_float(pcm: bytes) -> np.ndarray:
    """s16le mono bytes → float32 in [-1, 1]."""
    return np.frombuffer(pcm, dtype="<i2").astype(np.float32) / 32768.0


def _mel_filterbank(n_mels: int = N_MELS, n_fft: int = N_FFT, sr: int = SAMPLE_RATE) -> np.ndarray:
    def hz_to_mel(hz):
        return 2595.0 * np.log10(1.0 + hz / 700.0)

    def mel_to_hz(mel):
        return 700.0 * (10.0 ** (mel / 2595.0) - 1.0)

    mel_pts = np.linspace(hz_to_mel(50.0), hz_to_mel(sr / 2), n_mels + 2)
    hz_pts = mel_to_hz(mel_pts)
    bins = np.floor((n_fft + 1) * hz_pts / sr).astype(int)
    fb = np.zeros((n_mels, n_fft // 2 + 1))
    for m in range(1, n_mels + 1):
        lo, ctr, hi = bins[m - 1], bins[m], bins[m + 1]
        for k in range(lo, ctr):
            if ctr > lo:
                fb[m - 1, k] = (k - lo) / (ctr - lo)
        for k in range(ctr, hi):
            if hi > ctr:
                fb[m - 1, k] = (hi - k) / (hi - ctr)
    return fb


_FB = _mel_filterbank()
_WINDOW = np.hamming(FRAME)


def _logmel_frames(x: np.ndarray) -> np.ndarray:
    """(n_frames, N_MELS) log-mel energies of voiced-ish frames."""
    if len(x) < FRAME:
        return np.zeros((0, N_MELS))
    n = 1 + (len(x) - FRAME) // HOP
    idx = np.arange(FRAME)[None, :] + HOP * np.arange(n)[:, None]
    frames = x[idx] * _WINDOW
    spec = np.abs(np.fft.rfft(frames, N_FFT, axis=1)) ** 2
    mel = np.log(spec @ _FB.T + 1e-9)

    # keep frames with real speech energy (drop silence / room hiss)
    energy = frames.std(axis=1)
    keep = energy > max(0.004, float(np.percentile(energy, 40)))
    return mel[keep]


def raw_vector(pcm: bytes) -> np.ndarray | None:
    """Uncalibrated feature vector. None if too little speech."""
    mel = _logmel_frames(pcm_to_float(pcm))
    if mel.shape[0] < 20:  # <0.2s of voiced audio — not scoreable
        return None
    mu = mel.mean(axis=0)
    sd = mel.std(axis=0)
    shape = mu - mu.mean()  # spectral tilt/shape, level-independent
    return np.concatenate([shape, sd])


# Calibration "trained" by dojo/run_dojo.py on an ElevenLabs voice matrix:
# per-dimension whitening (subtract the population mean, divide by the
# population std) before cosine scoring — dims that vary between speakers get
# equal say, dims that vary with content/style get shrunk. Regenerated by the
# dojo; safe to ship without it (identity fallback).
try:  # pragma: no cover — exercised via dojo
    from .dsp_calibration import SIGMA as _CAL_SIGMA
    from .dsp_calibration import MU as _CAL_MU
    from .dsp_calibration import THRESHOLD as _CAL_THRESHOLD
    from .dsp_calibration import COHORT as _CAL_COHORT
except ImportError:
    _CAL_MU = _CAL_SIGMA = None
    _CAL_THRESHOLD = None
    _CAL_COHORT = None


def embed(pcm: bytes) -> np.ndarray | None:
    """Utterance embedding (whitened when calibrated), L2-normalized."""
    v = raw_vector(pcm)
    if v is None:
        return None
    if _CAL_MU is not None:
        v = (v - np.array(_CAL_MU)) / (np.array(_CAL_SIGMA) + 1e-9)
    return v / (np.linalg.norm(v) + 1e-9)


def profile_from(embeddings: list[np.ndarray]) -> np.ndarray:
    p = np.mean(np.stack(embeddings), axis=0)
    return p / (np.linalg.norm(p) + 1e-9)


def score(profile: np.ndarray, embedding: np.ndarray) -> float:
    """Cohort-z-normalized cosine when calibrated, plain cosine otherwise.

    z-norm: how much MORE similar is this speech to the owner's profile than
    to a cohort of reference voices — cancels utterance-level shifts (content,
    style, recording) that plain cosine can't.
    """
    s0 = float(np.dot(profile, embedding))
    if _CAL_COHORT:
        cohort = np.array(_CAL_COHORT)
        cs = cohort @ embedding
        return (s0 - float(cs.mean())) / (float(cs.std()) + 1e-6)
    return s0


def effective_threshold() -> float:
    return float(_CAL_THRESHOLD) if _CAL_THRESHOLD else DEFAULT_THRESHOLD


def verdict(profile: np.ndarray | None, pcm: bytes, threshold: float | None = None) -> tuple[str, float]:
    """('owner'|'other'|'unknown', score) for a ~1s audio window."""
    if threshold is None:
        threshold = effective_threshold()
    if profile is None:
        return "unknown", 0.0
    e = embed(pcm)
    if e is None:
        return "unknown", 0.0
    s = score(profile, e)
    return ("owner" if s >= threshold else "other"), s
